openapi: "3.0.0"
info:
  title: CityVizor fulltext search
  version: 0.1.0
paths:
  /search:
    get:
      operationId: search
      summary: "Search"
      parameters:
        - in: query
          name: query
          required: true
          schema:
            type: string
        - in: query
          name: profile
          required: false
          schema:
            type: string
      responses:
        '200':
          description: "Returned results"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Results'

components:
  schemas:
    Results:
      properties:
        invoices:
          type: array
          items:
            $ref: '#/components/schemas/InvoiceResult'
    InvoiceResult:
      required:
        - id
        - profile
        - year
        - type
        - item
        - paragraph
        - date
        - amount
      properties:
        id:
          type: integer
        profile:
          type: string
        year:
          type: integer
        event:
          type: string
        eventSrcId:
          type: string
        type:
          type: string
        item:
          type: integer
        paragraph:
          type: integer
        date:
          type: string
          format: date
        amount:
          type: number
        counterpartyId:
          type: number
        counterpartyName:
          type: string
        description:
          type: string

