# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CityVizor
email: cityvizor@otevrenamesta.cz
description: CityVizor je aplikace na přehledné zveřejnění výdajů obcí!
baseurl: "/cityvizor"
url: ""

# Build settings
markdown: kramdown

# Main menu
navigation:
- text: O aplikaci
  url: o-aplikaci/
  id: o-aplikaci
- text: Návody
  url: navody/
  id: navody
- text: Dokumentace
  url: dokumentace/
  id: dokumentace
- text: Data
  url: data/
  id: data
- text: Kontakt
  url: kontakt/
  id: kontakt
  
# Gems
gems: 
 - jekyll-redirect-from
 - jekyll-toc
